"""Add RSS feed models with named constraints

Revision ID: dca12d0d65ef
Revises: fe9391d68bcd
Create Date: 2025-02-25 12:47:04.879916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca12d0d65ef'
down_revision = 'fe9391d68bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_audio_content_feed', 'rss_feed', ['feed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_content', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audio_content_feed', type_='foreignkey')
        batch_op.drop_column('feed_id')

    # ### end Alembic commands ###
